/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import javax.swing.JOptionPane;
import javax.swing.text.Document;
import posto.Combustivel;
import posto.ServicosExtra;
import model.document.SomenteNumeros;


public class TelaPrincipal extends javax.swing.JFrame {

    //MODELOS
        Combustivel modeloCombustivel = new Combustivel();
        ServicosExtra modeloServExtra = new ServicosExtra();
        
    public TelaPrincipal() {
        initComponents();
        
        jTextFieldQtdCombustivel.setDocument(new SomenteNumeros());
        jFormattedTextFieldQtdOleo.setDocument(new SomenteNumeros());
        
        jLabelTanqueDiesel.setText(String.valueOf(modeloCombustivel.totalDieselTanque));
        jLabelTanqueEtanol.setText(String.valueOf(modeloCombustivel.totalEtanolTanque));
        jLabelTanqueGasolina.setText(String.valueOf(modeloCombustivel.totalGasolinaTanque));
        
        
        /*
        INICIAR COM LABELS DO OLEO DESATIVADOS
        */
        //OCULTAR LABEL 'MARCA DO OLEO'
        jLabel11.setVisible(false);
        //OCULTAR COMBOBOX COM LISTA DE OLEOS
        jComboBoxListaOleo.setVisible(false);
        //OCULTAR LABEL QTD OLEO
        jLabel12.setVisible(false);
        //OCULTAR LABEL 'VALOR POR LITRO'
        jLabelPrecoOleo.setVisible(false);
        //OCULTAR LABEL 'TOTAL SERV EXTRA'
        jLabel19.setVisible(false);
        //OCULTAR LABEL 'VALOR TOTAL SERV EXTRA'
        jLabelTotalServExtra.setVisible(false);
        //OCULTAR LABEL 'QTD'
        jLabel18.setVisible(false);
        //OCULTAR TEXTFIELD QTD
        jFormattedTextFieldQtdOleo.setVisible(false);
        //OCULTAR BOTAO
        jButtonCarrinhoOleo.setVisible(false);
        
        //SETAR VALORES ZEROS
        jTextFieldQtdCombustivel.setText("");
        jFormattedTextFieldQtdOleo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoCombustiivel = new javax.swing.ButtonGroup();
        buttonGroupMetodoPgto = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonDiesel = new javax.swing.JRadioButton();
        jRadioButtonGasolina = new javax.swing.JRadioButton();
        jRadioButtonEtanol = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelTotalCombustivel = new javax.swing.JLabel();
        jButtonAbastecer = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextFieldQtdCombustivel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jCheckBoxTrocaOleo = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxListaOleo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabelPrecoOleo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jRadioButtonAvista = new javax.swing.JRadioButton();
        jRadioButtonAte30d = new javax.swing.JRadioButton();
        jRadioButtonDepois30d = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabelTotalServExtra = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabelTanqueDiesel = new javax.swing.JLabel();
        jLabelTanqueEtanol = new javax.swing.JLabel();
        jLabelTanqueGasolina = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabelTotalFinal = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButtonCarrinhoOleo = new javax.swing.JButton();
        jFormattedTextFieldQtdOleo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("SELECIONE O TIPO DE COMBUSTÍVEL:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 16, -1, -1));

        jRadioButtonDiesel.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupTipoCombustiivel.add(jRadioButtonDiesel);
        jRadioButtonDiesel.setText("Diesel");
        jPanel2.add(jRadioButtonDiesel, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 50, -1, -1));

        jRadioButtonGasolina.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupTipoCombustiivel.add(jRadioButtonGasolina);
        jRadioButtonGasolina.setText("GASOLINA");
        jPanel2.add(jRadioButtonGasolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        jRadioButtonEtanol.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupTipoCombustiivel.add(jRadioButtonEtanol);
        jRadioButtonEtanol.setText("ETANOL");
        jPanel2.add(jRadioButtonEtanol, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 50, -1, -1));

        jLabel2.setText("PREÇO POR LITRO:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel3.setText("DIESEL");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 36, -1, -1));

        jLabel4.setText("GASOLINA");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 82, -1, -1));

        jLabel5.setText("ETANOL");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 59, -1, -1));

        jLabel6.setText("R$ 2.00");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 36, -1, -1));

        jLabel7.setText("R$4,00");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 82, -1, -1));

        jLabel8.setText("R$ 3,00");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 59, -1, -1));

        jLabel10.setText("LITROS");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 86, -1, -1));

        jLabel17.setText("TOTAL COMBUSTÍVEL:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 141, -1, -1));

        jLabelTotalCombustivel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTotalCombustivel.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jLabelTotalCombustivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 133, 85, 24));

        jButtonAbastecer.setText("+ CARRINHO");
        jButtonAbastecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbastecerActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAbastecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 82, 110, -1));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SAIR");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, -1, 50));

        jTextFieldQtdCombustivel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldQtdCombustivel.setText(" ");
        jPanel2.add(jTextFieldQtdCombustivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 40, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 810, 160));

        jLabel9.setText("SERVIÇOS EXTRAS:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 196, -1, -1));

        jCheckBoxTrocaOleo.setText("TROCA DE OLEO");
        jCheckBoxTrocaOleo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxTrocaOleoItemStateChanged(evt);
            }
        });
        jCheckBoxTrocaOleo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxTrocaOleoMouseClicked(evt);
            }
        });
        jPanel1.add(jCheckBoxTrocaOleo, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 218, -1, -1));

        jLabel11.setText("MARCA DO ÓLEO:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jComboBoxListaOleo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "LUBRAX", "SHELL", "CASTROL", "IPIRANGA" }));
        jComboBoxListaOleo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxListaOleoItemStateChanged(evt);
            }
        });
        jComboBoxListaOleo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxListaOleoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxListaOleoMouseEntered(evt);
            }
        });
        jComboBoxListaOleo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxListaOleoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxListaOleo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 150, -1));

        jLabel12.setText("PREÇO POR LITRO: ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 222, -1, -1));

        jLabelPrecoOleo.setText(" ");
        jPanel1.add(jLabelPrecoOleo, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 222, 72, -1));

        jLabel13.setText("FORMA PGTO:");

        buttonGroupMetodoPgto.add(jRadioButtonAvista);
        jRadioButtonAvista.setText("A VISTA");

        buttonGroupMetodoPgto.add(jRadioButtonAte30d);
        jRadioButtonAte30d.setText("ATÉ EM 30 D");

        buttonGroupMetodoPgto.add(jRadioButtonDepois30d);
        jRadioButtonDepois30d.setText("+30 D");

        jLabel14.setText("10% DESC");

        jLabel15.setText("VALOR NORMAL");

        jLabel16.setText("2% REAJUSTE");

        jButton1.setText("PAGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonAvista)
                                    .addComponent(jRadioButtonAte30d)
                                    .addComponent(jRadioButtonDepois30d))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonAvista)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonAte30d)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonDepois30d)))
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 369, -1, 210));

        jLabel19.setText("TOTAL SERV. EXTRA:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 255, -1, -1));

        jLabelTotalServExtra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTotalServExtra.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jLabelTotalServExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 80, 20));

        jLabel21.setText("DEPÓSITO ATUAL DE COMBUSTÍVEL:");

        jLabel22.setText("DIESEL");

        jLabel23.setText("ETANOL");

        jLabel24.setText("GASOLINA");

        jLabel28.setText("L");

        jLabel29.setText("L");

        jLabel30.setText("L");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel24)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(13, 13, 13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelTanqueEtanol, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(jLabelTanqueDiesel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTanqueGasolina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel30)))
                    .addComponent(jLabel21))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTanqueDiesel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(jLabel28)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabelTanqueEtanol, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel24)
                    .addComponent(jLabelTanqueGasolina, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 315, 230, -1));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setText("TOTAL FINAL A PAGAR");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 13, -1, -1));

        jLabelTotalFinal.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelTotalFinal.setForeground(new java.awt.Color(0, 0, 153));
        jPanel5.add(jLabelTotalFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 160, 50));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 230, 100));

        jLabel18.setText("QTD:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        jButtonCarrinhoOleo.setText("+ CARRINHO");
        jButtonCarrinhoOleo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarrinhoOleoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCarrinhoOleo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 110, -1));

        jFormattedTextFieldQtdOleo.setText(" ");
        jPanel1.add(jFormattedTextFieldQtdOleo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        
        String nomeCombustivel = "";
        String servExtra = "";
        
        String descServExtra = "";
                
        if (jRadioButtonDiesel.isSelected()==true){
            nomeCombustivel = "DIESEL";
            
            jLabelTanqueDiesel.setText(String.valueOf(modeloCombustivel.totalDieselTanque - modeloCombustivel.qtdLitros));
            
        }else if(jRadioButtonEtanol.isSelected()==true){
            nomeCombustivel = "ETANOL";
            jLabelTanqueEtanol.setText(String.valueOf(modeloCombustivel.totalEtanolTanque - modeloCombustivel.qtdLitros));
        }else if (jRadioButtonGasolina.isSelected()==true){
            nomeCombustivel = "GASOLINA";
            jLabelTanqueGasolina.setText(String.valueOf(modeloCombustivel.totalGasolinaTanque - modeloCombustivel.qtdLitros));
        }
        
        if (modeloServExtra.valorTotalVendaOleo==0){
            servExtra = "NAO";
        }else{
            servExtra = "SIM";
            
            descServExtra = ""
                    + "OLEO COMPRADO: "+modeloServExtra.nomeOleo+"\n"
                    + "QUANTIDADE: "+modeloServExtra.qtdOleo+"\n"
                    + "VALOR = R$ "+modeloServExtra.valorTotalVendaOleo+"\n\n";
        }
        
        String msg = "SEU PEDIDO\n\n"
                + "COMBUSTIVEL = "+nomeCombustivel+"\n"
                + "QTD SOLICITADA = "+modeloCombustivel.qtdLitros+" LITROS\n"
                + "VALOR = R$ "+modeloCombustivel.totalPrecoCombustivel+"\n"
                + "-----------------------------------------\n"
                + "SERVICO EXTRA:\n"
                + ""+servExtra+"\n"
                + ""+descServExtra+"\n"
                + "-----------------------------\n\n"
                + "TOTAL FINAL = R$ "+jLabelTotalFinal.getText();
        
        //JOptionPane.showMessageDialog(null, msg,"RECIBO",-1);

    
        double valorFinal = Double.parseDouble(jLabelTotalFinal.getText().replace("R$ ", ""));
        String desconto = "";
        
        if (jRadioButtonAvista.isSelected()==true){
            valorFinal = valorFinal - (valorFinal*0.10);
            desconto = "DESCONTO DE 10%";
        }
        else if (jRadioButtonAte30d.isSelected()==true){
            //NAO ALTERA VALOR
            desconto = "SEM DESCONTOS!";
            
        }else if (jRadioButtonDepois30d.isSelected()==true){
            valorFinal = valorFinal + (valorFinal*0.02);
            desconto = "ACRÉSCIMO DE 2%";
        }
        msg = msg + "\n"
                + "-------------------\n"
                + "DESCONTO: "+desconto+"\n"
                + "-------------------\n"
                + "TOTAL A PAGAR = R$ "+valorFinal;
        
        JOptionPane.showMessageDialog(null, msg,"RECIBO",-1);
        
        
                //SETAR DEFAULT
        
        modeloCombustivel.qtdLitros = 0;
        modeloCombustivel.totalPrecoCombustivel = 0;
        modeloServExtra.valorTotalVendaOleo = 0;
        
        jTextFieldQtdCombustivel.setText("");
        jLabelTotalCombustivel.setText("");
        jCheckBoxTrocaOleo.setSelected(false);
        jFormattedTextFieldQtdOleo.setText("");
        jLabelPrecoOleo.setText("");
        jLabelTotalServExtra.setText("");
        jLabelTotalFinal.setText("");
        
        //OCULTAR LABEL 'MARCA DO OLEO'
        jLabel11.setVisible(false);
        //OCULTAR COMBOBOX COM LISTA DE OLEOS
        jComboBoxListaOleo.setVisible(false);
        //OCULTAR LABEL QTD OLEO
        jLabel12.setVisible(false);
        //OCULTAR LABEL 'VALOR POR LITRO'
        jLabelPrecoOleo.setVisible(false);
        //OCULTAR LABEL 'TOTAL SERV EXTRA'
        jLabel19.setVisible(false);
        //OCULTAR LABEL 'VALOR TOTAL SERV EXTRA'
        jLabelTotalServExtra.setVisible(false);
        //OCULTAR LABEL 'QTD'
        jLabel18.setVisible(false);
        //OCULTAR TEXTFIELD QTD
        jFormattedTextFieldQtdOleo.setVisible(false);
        //OCULTAR BOTAO
        jButtonCarrinhoOleo.setVisible(false);
        
        jRadioButtonDiesel.setSelected(false);
        jRadioButtonEtanol.setSelected(false);
        jRadioButtonGasolina.setSelected(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBoxTrocaOleoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxTrocaOleoMouseClicked

        //SE A COMBOBOX FOR SELECIONADA
        if(jCheckBoxTrocaOleo.isSelected() == true){
        //MOSTRAR LABEL 'MARCA DO OLEO'
        jLabel11.setVisible(true);
        //MOSTRAR COMBOBOX COM LISTA DE OLEOS
        jComboBoxListaOleo.setVisible(true);
        //MOSTRAR LABEL QTD OLEO
        jLabel12.setVisible(true);
        //MOSTRAR LABEL 'VALOR POR LITRO'
        jLabelPrecoOleo.setVisible(true);
        //MOSTRAR LABEL 'TOTAL SERV EXTRA'
        jLabel19.setVisible(true);
        //MOSTRAR LABEL 'VALOR TOTAL SERV EXTRA'
        jLabelTotalServExtra.setVisible(true);
        //MOSTRAR LABEL 'QTD'
        jLabel18.setVisible(true);
        //MSTRAR TEXTFIELD QTD
        jFormattedTextFieldQtdOleo.setVisible(true);
        //MOSTRAR BOTAO
        jButtonCarrinhoOleo.setVisible(true);
        
        }else{
        //OCULTAR LABEL 'MARCA DO OLEO'
        jLabel11.setVisible(false);
        //OCULTAR COMBOBOX COM LISTA DE OLEOS
        jComboBoxListaOleo.setVisible(false);
        //OCULTAR LABEL QTD OLEO
        jLabel12.setVisible(false);
        //OCULTAR LABEL 'VALOR POR LITRO'
        jLabelPrecoOleo.setVisible(false);
        //OCULTAR LABEL 'TOTAL SERV EXTRA'
        jLabel19.setVisible(false);
        //OCULTAR LABEL 'VALOR TOTAL SERV EXTRA'
        jLabelTotalServExtra.setVisible(false);
        //OCULTAR LABEL 'QTD'
        jLabel18.setVisible(false);
        //OCULTAR TEXTFIELD QTD
        jFormattedTextFieldQtdOleo.setVisible(false);
        //OCULTAR BOTAO
        jButtonCarrinhoOleo.setVisible(false);
        }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTrocaOleoMouseClicked

    private void jButtonAbastecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbastecerActionPerformed
        
        //VARIAVEL PARA RECEBER VALOR DIGITADO
        String strQtdCombustivel = jTextFieldQtdCombustivel.getText();

        //VALOR FINAL
        double vfinal = 0;
        
        //SE QTD FOR=VAZIO
        if (strQtdCombustivel.equals("")){
            
        }
        //SE DISEL FOR SELECIONADO
        else if(jRadioButtonDiesel.isSelected()==true){
            modeloCombustivel.qtdLitros = Double.parseDouble(strQtdCombustivel);
            modeloCombustivel.totalPrecoCombustivel = modeloCombustivel.precoDiesel * modeloCombustivel.qtdLitros;
        }
        //SE ETANOL FOR SELECIONADO
        else if (jRadioButtonEtanol.isSelected()==true){
            modeloCombustivel.qtdLitros = Double.parseDouble(strQtdCombustivel);
            modeloCombustivel.totalPrecoCombustivel = modeloCombustivel.precoEtanol * modeloCombustivel.qtdLitros;
        }
        //SE GASOLINA FOR SELECIONADO
        else if (jRadioButtonGasolina.isSelected()==true){
            modeloCombustivel.qtdLitros = Double.parseDouble(strQtdCombustivel);
            modeloCombustivel.totalPrecoCombustivel = modeloCombustivel.precoGasolina * modeloCombustivel.qtdLitros;
        }
        
        
        jLabelTotalCombustivel.setText("R$ "+String.valueOf(modeloCombustivel.totalPrecoCombustivel));
        
        //ENVIAR PARA O TOTAL FINAL
        if(modeloServExtra.valorTotalVendaOleo == 0){
            jLabelTotalFinal.setText("R$ "+modeloCombustivel.totalPrecoCombustivel);
        }
        else{
            double totalVenda = modeloCombustivel.totalPrecoCombustivel + modeloServExtra.valorTotalVendaOleo;
            
            jLabelTotalFinal.setText("R$ "+String.valueOf(totalVenda));
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAbastecerActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //FECHAR TELA
        dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBoxListaOleoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxListaOleoActionPerformed

        
        
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxListaOleoActionPerformed

    private void jCheckBoxTrocaOleoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxTrocaOleoItemStateChanged



        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTrocaOleoItemStateChanged

    private void jComboBoxListaOleoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxListaOleoItemStateChanged
                        //SE A TROCA DE OLEO FOR SELECIONADA, FAÇA
        if (jCheckBoxTrocaOleo.isSelected()==true){
        
            //RECEBER OLEO SELECIONADO
            String oleoSelecionado = (String)jComboBoxListaOleo.getSelectedItem();
            //VERIFICAR QUAL OLEO FOI SELECIONADO
            if(oleoSelecionado.equals("SELECIONE")){
                //SETAR ZERO
                jLabelPrecoOleo.setText("0");
                
            }
            else if(oleoSelecionado.equals("LUBRAX")){
                //EXIBIR VALOR DO LUBRAX
                jLabelPrecoOleo.setText("R$ "+String.valueOf(modeloServExtra.valorLubrax));
                jButtonCarrinhoOleo.setVisible(true);
            }
            else if(oleoSelecionado.equals("SHELL")){
                //EXIBIR VALOR DO SHELL
                jLabelPrecoOleo.setText("R$ "+String.valueOf(modeloServExtra.valorShell));
                jButtonCarrinhoOleo.setVisible(true);
            }
            else if(oleoSelecionado.equals("CASTROL")){
                //EXIBIR VALOR DO CASTROL
                jLabelPrecoOleo.setText("R$ "+String.valueOf(modeloServExtra.valorCastrol));
                jButtonCarrinhoOleo.setVisible(true);
            }
            
            else if(oleoSelecionado.equals("IPIRANGA")){
                //EXIBIR VALOR DO IPIRANGA
                jLabelPrecoOleo.setText("R$ "+String.valueOf(modeloServExtra.valorIpiranga));
                jButtonCarrinhoOleo.setVisible(true);
            }
        
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxListaOleoItemStateChanged

    private void jButtonCarrinhoOleoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarrinhoOleoActionPerformed

        //EXIBIR TOTAL DO SERVICO EXTRA
        int qtdOleo = Integer.parseInt(jFormattedTextFieldQtdOleo.getText());
        double precoOleo = Double.parseDouble(jLabelPrecoOleo.getText().replace("R$ ", ""));
        
        //RECEBER VALOR TOTAL DOS SERVICOS REALIZADOS
        double vtotal = 0;
        
        modeloServExtra.valorTotalVendaOleo = qtdOleo * precoOleo;
 
        if(modeloCombustivel.totalPrecoCombustivel == 0){
            
            jLabelTotalFinal.setText("R$ "+String.valueOf(modeloServExtra.valorTotalVendaOleo));
            jLabelTotalServExtra.setText("R$ "+modeloServExtra.valorTotalVendaOleo);
            modeloServExtra.nomeOleo = (String)jComboBoxListaOleo.getSelectedItem();
            modeloServExtra.qtdOleo = qtdOleo;
            
        }else{
            
            vtotal = modeloServExtra.valorTotalVendaOleo + modeloCombustivel.totalPrecoCombustivel;            
            jLabelTotalFinal.setText("R$ "+String.valueOf(vtotal));
            
            modeloServExtra.nomeOleo = (String)jComboBoxListaOleo.getSelectedItem();
            modeloServExtra.qtdOleo = qtdOleo;
            
            jLabelTotalServExtra.setText("R$ "+modeloServExtra.valorTotalVendaOleo);
        }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCarrinhoOleoActionPerformed

    private void jComboBoxListaOleoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxListaOleoMouseEntered

        


        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxListaOleoMouseEntered

    private void jComboBoxListaOleoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxListaOleoMouseClicked



        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxListaOleoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupMetodoPgto;
    private javax.swing.ButtonGroup buttonGroupTipoCombustiivel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAbastecer;
    private javax.swing.JButton jButtonCarrinhoOleo;
    private javax.swing.JCheckBox jCheckBoxTrocaOleo;
    private javax.swing.JComboBox<String> jComboBoxListaOleo;
    private javax.swing.JTextField jFormattedTextFieldQtdOleo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPrecoOleo;
    private javax.swing.JLabel jLabelTanqueDiesel;
    private javax.swing.JLabel jLabelTanqueEtanol;
    private javax.swing.JLabel jLabelTanqueGasolina;
    private javax.swing.JLabel jLabelTotalCombustivel;
    private javax.swing.JLabel jLabelTotalFinal;
    private javax.swing.JLabel jLabelTotalServExtra;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButtonAte30d;
    private javax.swing.JRadioButton jRadioButtonAvista;
    private javax.swing.JRadioButton jRadioButtonDepois30d;
    private javax.swing.JRadioButton jRadioButtonDiesel;
    private javax.swing.JRadioButton jRadioButtonEtanol;
    private javax.swing.JRadioButton jRadioButtonGasolina;
    private javax.swing.JTextField jTextFieldQtdCombustivel;
    // End of variables declaration//GEN-END:variables
}
